### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by Tamerz** [puppetlabs/puppetlabs-tagmail#180]
In the "Description" section there is a link to "report processor" (https://docs.puppetlabs.com/guides/reporting.html) that is dead.

**Comment by Disha-maker** [comment]
Dead link paragraph removed - check the link below with the new changes https://github.com/puppetlabs/puppetlabs-tagmail

**Comment by Disha-maker** [comment]
A new PR is raised to address the issue of broken links within the read me file, please close this issue if the new PR is all good
